### PR TITLE
Fix EZP-24825:  add and use optional odf.ini variable to handle odf export template path

### PR DESCRIPTION
**Pull request by Opencontent**

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
Jira issue: https://jira.ez.no/browse/EZP-24825

**Comment by andrerom** [comment]
+1 *for 5.4.x*

**Comment by bdunogier** [comment]
+1 as well

**Comment by FrancescoN** [comment]
any news?

**Comment by bdunogier** [comment]
Manually merged (to change the issue # in the message) to c1342bc (master) and e6d43b8 (stable-5.3).

Thank you @FrancescoN.

**Pull request closed without merging**
